NVIDIA-NeMo/Curator

- .pre-commit-config.yaml
- nemo_curator/modules/__init__.py
> Fix Noisy CUDA Shutdown

- docs/user-guide/PersonalIdentifiableInformationIdentificationAndRemoval.rst
- examples/classifier_filtering.py
- examples/find_pii_and_deidentify.py
- nemo_curator/filters/__init__.py
- nemo_curator/filters/classifier_filter.py
- nemo_curator/modifiers/pii_modifier.py
- nemo_curator/modules/filter.py
- nemo_curator/modules/modify.py
- nemo_curator/modules/task.py
- nemo_curator/scripts/find_pii_and_deidentify.py
- nemo_curator/utils/decorators.py
- nemo_curator/utils/module_utils.py
- tests/test_filters.py
- tutorials/tinystories/main.py
Refactors batched to be in a decorator. This frees the user from having to be knowledgable about how the underlying `DocumentFilter` or `DocumentModifier` when initializing `ScoreFilter` or `Modify` respectively.
Unit tests pass. The following scripts were manually tested and work properly.
```
examples/classifier_filtering.py
examples/find_pii_and_deidentify.py
nemo_curator/scripts/find_pii_and_deidentify.py
tutorials/tinystories/main.py
```
The examples and other scripts have been manually tested to work.
> Add batched decorator

- nemo_curator/modules/filter.py
- nemo_curator/modules/task.py
Prevents Dask from passing `pd.NA` to the filters for type inference on the scoring and filtering functions. Also fixes some issues with task decontamination working with pandas 2.0 strings and exploding.
With task decontamination, we convert the document text column (dtype=string) to a list of split documents (dtype=object). When calling explode on this column of split documents, the column maintains its object datatype even though now it's only strings. We need to recast the column for newer versions of pandas/dask where string and object are different datatypes.
> Fix metadata inference with pandas and dask

- nemo_curator/filters/code.py
- nemo_curator/modules/__init__.py
Addresses #31 by disabling multiprocessing for PyTorch according to advice gathered from [this issue](https://github.com/pytorch/pytorch/issues/123329). Essentially, we need to set `os.environ["TORCHINDUCTOR_COMPILE_THREADS"] = "1"` before PyTorch is imported and [this variable](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/config.py#L397) is initialized. I also moved the nemo import statement to inside of the filter so that any performance impact is minimized (though I observed no speed degradation in my tests).
> Disable PyTorch Compile Multiprocessing

- nemo_curator/modules/add_id.py
- nemo_curator/scripts/add_id.py
- nemo_curator/utils/module_utils.py
- tests/test_add_id.py
Improves the speed of the add id module by reducing the size of the task graph. However, this new method uses a different id structure. If users need the old format that is guaranteed to be ordered, they can still access by passing in a definitive `start_id`.
> Improve speed of AddId module

- tests/test_fuzzy_dedup.py
The latest version bumps also resulted in pandas 2.x being pulled in which brought in subtle differences in handling around object/list types. 
This PR fixes failing GPU tests after the bump
> Fix failing GPU tests with latest pandas bump

- docs/user-guide/CPUvsGPU.rst
- docs/user-guide/KubernetesCurator.rst
- docs/user-guide/index.rst
- examples/k8s/create_dask_cluster.py
>  Adds Nemo Curator K8s example

- docs/user-guide/QualityFiltering.rst
- nemo_curator/filters/classifier_filter.py
- nemo_curator/modifiers/__init__.py
- nemo_curator/modifiers/pii_modifier.py
- tests/test_filters.py
- tests/test_pii_accuracy.py
Fixes an issue reported by @Maghoumi. When the PII Modifier takes in a partition that has been partially filtered, it does not respect the subset of the partition that was given to it. It overrides the index, and the modifications get applied to elements they were not supposed to.
> Fix indexing in PII Modifier

- config/fasttext_langid.yaml
- nemo_curator/__init__.py
- nemo_curator/filters/classifier_filter.py
When reading jsonl files, Dask automatically parses all objects as strings. Therefore, we decide to disable the automatic string conversion globally since we have seen this problem in the langid examples too.
> Disable string conversion globally

- nemo_curator/__init__.py
- nemo_curator/modules/fuzzy_dedup.py
- tests/test_fuzzy_dedup.py
One of the functions in jaccard computation for Fuzzy dedup assume the text field of the dataset to be called `text` and doesn't use the `text_field` information provided. 
Additionally, explicitly set query planning to false.
> Fuzzy Dedup:  Use text_field instead of hardcoded text column

- docs/user-guide/DistributedDataClassification.rst
Fix https://github.com/NVIDIA/NeMo-Curator/issues/91
There is a reference to a wrong path/file in this document.
This commit fixes it.
```python
```
> Fix #91 - Incorrect reference to domain_classifier_example.py

- README.md
- setup.py
Updates the documentation for the `0.3.0` release on PyPi
N/A
> Update documentation for new version

- nemo_curator/__init__.py
- tests/__init__.py
As far as I can tell, the existing logic used to disable query-planning isn't really doing anything. As soon as `dask.dataframe` is imported, changing the `"dataframe.query-planning"` configuration will no longer have an effect.
> Make sure query-planning is disabled for now

- nemo_curator/modules/fuzzy_dedup.py
This PR shuffles the `connected_components` output by group to ensure that all documents belonging to the same duplicate group/component end up in the same partition. The motivation for doing this ensure the example showcasing document removal work as intended: https://github.com/NVIDIA/NeMo-Curator/blob/main/examples/fuzzy_deduplication.py#L87.
N/A
> Shuffle CC result on group before writing out

- docs/user-guide/index.rst
Added links to tutorials
```python
```
> Added tutorials to index.rst

- nemo_curator/utils/gpu_utils.py
- nemo_curator/utils/import_utils.py
Fixes #109 
#27 Added support for installing a CPU only build of nemo_curator that works in cpu environments. However it didn't account for the case where the GPU version of curator was installed but the package was being used in CPU only environments. 
One case this happens is when using the NeMo-FW container in CPU only environments. This pr extends the safe_import mechanism to fail on `importError` instead of `ModuleNotFoundError` for cases where the module was present but import failed due to missing GPUs.
One downside to this approach is that there's an implicit assumption that the importError on GPU packages stem from a missing GPU environment or missing packages, so we may wrongly classify other issues on import of these packages into the same bucket.
```bash
pip install …
```
> Fix nemo_curator import in CPU only environment when GPU packages are installed.

- nemo_curator/utils/distributed_utils.py
- tests/test_io.py
- tests/test_seperate_by_metadata.py
Closes #89 
Adds an option to handle scenarios where there are multiple filenames in a single partition when writing with filename. 
This is typically true when files are read in with `files_per_partition` > 1.
```python
dataset = DocumentDataset.read_json(path, files_per_partition=5, include_filename=True)
write_to_disk(dataset.df, output_file_dir=path, write_to_filename=True)
```
> Allow multiple filenames per partition when separating by metadata

- examples/fuzzy_deduplication.py
- examples/slurm/start-slurm.sh
- nemo_curator/__init__.py
- tests/__init__.py
Importing newer versions of dask (tested with 2024.5) set `dataframe.query-planning` to None instead of `True` or `False`, but the `None` case defaults to using query planning. This PR extends the check to `None` to raise relevant errors w/ newer versions of dask.
N/A
> Stricter check for query planning.

- tutorials/distributed_data_classification/distributed_data_classification.ipynb
> Add DataFrame example to Distributed Data Classification tutorial

- setup.py
The original issue with [justext](https://github.com/NVIDIA/NeMo-Curator/issues/26) was fixed in the latest [patch](https://github.com/miso-belica/jusText/releases/tag/v3.0.1) so the [import error](https://github.com/NVIDIA/NeMo-Curator/issues/26) we saw earlier should be gone now.
N/A
> Remove lxml installation

- nemo_curator/utils/fuzzy_dedup_utils/shuffle_utils.py
dask-cuda 24.06 + explicit comms leads to incorrect results in some cases as mentioned in #134 and will be fixed via https://github.com/rapidsai/dask-cuda/pull/1356.
This disables going via explicit comms shuffle with dask-cuda 24.06 to avoid potentially incorrect results.
N/A
> Skip explicit comms shuffle for dask-cuda 24.06

- nemo_curator/services/nemo_client.py
- setup.py
> Fix bug with torch rmm and nemo

- nemo_curator/filters/code.py
While reading about code filters, I have noticed a couple of duplicated assignments in the code.
```python
```
> Fix #161. Remove duplicated assigments in GeneralCommentToCodeFilter

- tutorials/peft-curation-with-sdg/config/sem_dedup_config.yaml
- tutorials/peft-curation-with-sdg/main.py
Reduce the ratio of synthetic samples to lower API calls.
Reduce the cluster size for Sem Dedupe.
> [Tutorials] Reduce the cluster size for the SGD + PEFT notebook

- docs/user-guide/gpudeduplication.rst
- nemo_curator/scripts/fuzzy_deduplication/connected_components.py
Fixes a few things I found while testing the dedup scripts recently.
- The arg for jaccard similarity threshold doesn't work if you specify a floating point number, since its type is int. You get this error:
```
Computes connected component: error: argument --jaccard-threshold: invalid int value: '0.8'
```
- The docs have the arg for `--jaccard-pairs-path` misspelled to `--jaccard-pairs_path`
N/A
> Fix a few bugs in fuzzy dedup and docs

- nemo_curator/filters/code.py
Hi!
I have noticed a couple of small changes in the code that can improve its performance:
By refactoring score_document as suggested, it will run between 2x and 3x faster, and will reduce by half the memory footprint.
By refactoring '_line_statistics' as suggested, it can run about 21% faster.
Hope it helps!
Regards,
Miguel
> Fix 177. Improve score_document and _line_statistics performance

- setup.py
jusText depends on `lxml` and `lxml_html_clean`. Both should be possible to install through `lxml[html_clean]`, which is what jusText does. However, pip is (sometimes) unable to find the `[html_clean]` extra. To prevent errors going forward, I am installing this directly in our `setup.py`.
N/A
> Fix error in jusText

- docs/user-guide/download.rst
- docs/user-guide/semdedup.rst
Copyedited download.rst and semdedup.rst files for NeMo Pre-release.
> Update nemo curator files

- examples/slurm/container-entrypoint.sh
- setup.py
Bumps min Rapids version to 24.8 which is now out with perf improvements around long strings among many others.
Also adds `--enable-cudf-spill` option to slurm setup scripts to support cudf spilling.
N/A
```python
```
> Bump min Rapids versions to 24.8

- examples/classifiers/aegis_example.py
- examples/classifiers/domain_example.py
- examples/classifiers/fineweb_edu_example.py
- examples/classifiers/quality_example.py
Fixes minor bug discovered when reviewing https://github.com/NVIDIA/NeMo-Curator/pull/168.
> Remove extra `parse_args()` in classifier examples

- .github/workflows/test.yml
- tests/test_download.py
Sometimes when running our CI we will randomly run into a
```
FAILED tests/test_download.py::TestDownload::test_uneven_common_crawl_range - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
This PR marks the test as flaky and attempts to rerun it a couple times. I got the idea from when I was working on the Dask-SQL project and opened a PR https://github.com/dask-contrib/dask-sql/pull/1021. LMK if this looks useful for us.
> Rerun flaky PyTest

- tutorials/peft-curation-with-sdg/README.md
- tutorials/peft-curation-with-sdg/main.py
- Fixes an issue where the OpenAI client would fail to initialize if an API key is not provided.
- Add links to the NeMo FW tutorial for model fine-tuning.
> [Tutorials] Fix API key missing errors in the SDG tutorial

- README.md
- pyproject.toml
- setup.py
Currently the installation using `pip install .` doesn't work. We add instructions to pre-install `cython` to make it work.
`nemo_toolkit` depends on `YouTokenToMe` (and that requires Cython to exist). This is also _addressed_ in our `.github/workflows/test.yml` 
https://github.com/NVIDIA/NeMo-Curator/blob/2e0af575e65b73b7cf9455d36a68c5dba51a6553/.github/workflows/test.yml#L40 
Even `nemo_toolkit` requires an explicit installation of `Cython` before installing `nemo_toolkit`
https://github.com/NVIDIA/NeMo/blob/a777a442c43cd2092684c8b8f06701ed62134a9f/README.md#pip
However once `nemo_toolkit` 2.x is released we might be able to resolve this since https://github.com/NVIDIA/NeMo/pull/8322/ has been merged. In future we can also consider moving `nemo_toolkit` as an optional dependency since …
> Update Readme instruction to install cython

- nemo_curator/modules/__init__.py
- nemo_curator/modules/config.py
- nemo_curator/modules/fuzzy_dedup.py
- nemo_curator/scripts/fuzzy_deduplication/buckets_to_edges.py
- nemo_curator/utils/fuzzy_dedup_utils/shuffle_utils.py
- tests/test_fuzzy_dedup.py
- tests/test_semdedup.py
The existing Minhash based Fuzzy Dedup algo has a computationally expensive false positive check comprising of the `map_buckets`, `jaccard_shuffle` & `jaccard_compute` stages.
This PR aims to allow an alternative codepath allowing skipping these computationally expensive operations and directly going from LSH buckets to graph creation, allowing significant perf gains at the cost of ~1-2% tokens depending on the chose initial config and dataset.
TODO:
Add perf results
```python
fuzzy_dup_config = FuzzyDuplicatesConfig(false_positive_check=False)
...
```
> Add option to skip false positive checks during Fuzzy Deduplication

- nemo_curator/__init__.py
- nemo_curator/modules/config.py
- nemo_curator/modules/fuzzy_dedup.py
- nemo_curator/scripts/fuzzy_deduplication/compute_minhashes.py
- nemo_curator/scripts/fuzzy_deduplication/minhash_lsh.py
- nemo_curator/utils/distributed_utils.py
- nemo_curator/utils/fuzzy_dedup_utils/shuffle_utils.py
Fuzzy deduplication is currently accelerated via cuDF which until release 24.04 had a limit that a string column could not exceed int32 number of characters. Consequently some defaults and core logic in the deduplication pipeline aims to mitigate errors for cases where we may exceed this value.
Starting 24.06, cuDF has experimental support for longer strings (int64 number of chars), and this PR attempts to change defaults and simplify logic around handling long strings.
> Update Fuzzy dedup params for long strings support.

- .github/workflows/test.yml
- tests/test_download.py
Removes changes from https://github.com/NVIDIA/NeMo-Curator/pull/218. Since `test_uneven_common_crawl_range` is very flaky, we skip it for now. I will also open an issue for possibly re-adding it in the future.
> Remove flaky PyTest

- nemo_curator/scripts/filter_documents.py
Makes the id field optional for the `filter_docments` utility. It is only used if the user wants to attach each score to the corresponding id when writing out scores separately, so this does not need to be specified most of the time.
N/A
> Make id field optional for filtering

- nemo_curator/utils/distributed_utils.py
Since https://github.com/rapidsai/dask-cuda/pull/1362 is merged we don't need to rely on `client.run(_enable_spilling)` and can just pass that arg to `LocalCUDACluster`
> Add `enable_cudf_spill` to LocalCudaCluster

- nemo_curator/scripts/separate_by_metadata.py
- nemo_curator/utils/file_utils.py
- tests/test_separate_by_metadata.py
Fix #255 - Improve separate_by_metadata performance when dealing with jsonl files
This PR improves separate_by_metadata performance a minimum of 3x, while reducing the memory needs from O(N) to O(1).
The above translates to less OOMs, better CPU utilization, and constant memory usage (around 11GB in a 500GB server).
I have also added a new functionality that allows to select which fields to keep, or which fields to exclude. This is interesting, for instance, after applying a quality classifier, where some user would like to keep only "High" quality documents.
Hope it helps!
> Fix 255 - Improve separate_by_metadata performance for jsonl files

- tutorials/tinystories/main.py
Lowers the default number of workers in the tinystories tutorial so it is less likely to OOM.
N/A
> Lower nworkers for tinystories tutorial to avoid OOM

- examples/translation_example.py
- nemo_curator/classifiers/aegis.py
- nemo_curator/classifiers/fineweb_edu.py
- nemo_curator/scripts/semdedup/clustering.py
- tests/test_semdedup.py
- tutorials/distributed_data_classification/distributed_data_classification.ipynb
- tutorials/single_node_tutorial/single_gpu_tutorial.ipynb
Since https://github.com/NVIDIA/NeMo-Curator/pull/139 is merged, we don't need to be explicitly setting `DASK_DATAFRAME__QUERY_PLANNING=False` anymore.
> Remove `DASK_DATAFRAME__QUERY_PLANNING` environment variable

- nemo_curator/image/classifiers/nsfw.py
Changes the NSFW model from one that takes ViT-H embeddings as input into one that takes ViT-L embeddings as input.
No change
> Change NSFW Model

- tutorials/peft-curation-with-sdg/README.md
- tutorials/peft-curation-with-sdg/main.py
This PR ensures that users can run the PEFT SDG tutorial using arbitrary API endpoints by exposing the URL that is used for synthetic data generation.
> [Tutorials] Update the SDG tutorial and expose the inference endpoint

- nemo_curator/datasets/doc_dataset.py
- nemo_curator/utils/distributed_utils.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/180.
All of these will now work:
(1) [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html) and [cuDF](https://docs.rapids.ai/api/cudf/legacy/user_guide/api_docs/api/cudf.read_json/) `read_json` do not support a `columns` parameter, so we read in the entire DataFrame and then remove unwanted columns behind the scenes.
```
dataset = DocumentDataset.read_json(dataset_path, columns=["col1", "col2"])
```
(2) [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_parquet.html) and [cuDF](https://docs.rapids.ai/api/cudf/latest/user_guide/api_docs/api/cudf.read_parquet/) `read_parquet` both support a `columns` parameter, so we are able to take advantage of this functionality.
```
dataset = …
```
> Specify `columns` when reading files with `DocumentDataset`

- nemo_curator/datasets/doc_dataset.py
- nemo_curator/utils/distributed_utils.py
- tests/test_io.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/293.
> Write to file without including "filename" column

- .pre-commit-config.yaml
This pull request introduces improvements to the `.pre-commit-config.yaml` file, focusing on enhancing the pre-commit hook configuration. This PR closes: https://github.com/NVIDIA/NeMo-Curator/issues/290
Key updates:
- Ensure commits are signed-off, enforcing commit message compliance.
- Remind developers to install pre-commit hooks if missing, reducing setup errors.
```bash
(nemo_curator_dev) vjawa@dgx11:~/NeMo-Curator$ git add .pre-commit-config.yaml
(nemo_curator_dev) vjawa@dgx11:~/NeMo-Curator$ git commit -m 'check if signoff warning is raised'
```
```bash
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check yaml............................................................... …
```
> [REVIEW] Add pre-commit hook for DCO and pre-commit check

- nemo_curator/modules/fuzzy_dedup.py
- nemo_curator/scripts/fuzzy_deduplication/connected_components.py
This pull request includes several changes to the `nemo_curator/modules/fuzzy_dedup.py` file, focusing on removing the `convert_str_ids` functionality, optimizing performance, and improving logging. 
The most important changes are:
* Removed the `convert_str_ids` parameter and its associated logic from the `__init__` method and other methods in `nemo_curator/modules/fuzzy_dedup.py`. [[1]](diffhunk://#diff-b836d89c298548dd47480ece278782f030d04e2beb421c59c0e546718aede6c3L472) [[2]](diffhunk://#diff-b836d89c298548dd47480ece278782f030d04e2beb421c59c0e546718aede6c3L1408) [[3]](diffhunk://#diff-b836d89c298548dd47480ece278782f030d04e2beb421c59c0e546718aede6c3L1418) [[4]](diffhunk://#diff-b836d89c298548dd47480ece278782f030d04e2beb421c59c0e546718aede6c3L1482-R1483) …
> [REVIEW] Speedup Connected Components

- docs/user-guide/gpudeduplication.rst
- examples/fuzzy_deduplication.py
- nemo_curator/modules/fuzzy_dedup.py
- nemo_curator/utils/fuzzy_dedup_utils/shuffle_utils.py
- tests/test_fuzzy_dedup.py
Check `len(merged_df) == 0`, if so won't bother. 
Vibhu in #302 added
1. connected_components.parquet
2. final_dedup_encoded_jaccard_pair.parquet
This PR adds
1. encoded_jaccard_pair
2. dedup_parsed_id
3. anchor_docs_with_bk
4. jaccard_similarity_results.parquet
These were already being overwritten 
1. _buckets.parquet
2. _minhashes.parquet
3. _edges.parquet
We are overwritten this
1. shuffled_docs.parquet
```python
```
> Fix Jaccard Shuffle Error when Result is Empty + Overwrite using fuzzy_dedup cache

- nemo_curator/classifiers/aegis.py
- nemo_curator/classifiers/base.py
- nemo_curator/classifiers/domain.py
- nemo_curator/classifiers/fineweb_edu.py
- nemo_curator/classifiers/quality.py
- nemo_curator/scripts/classifiers/aegis_classifier_inference.py
- nemo_curator/scripts/classifiers/domain_classifier_inference.py
- nemo_curator/scripts/classifiers/fineweb_edu_classifier_inference.py
- nemo_curator/scripts/classifiers/quality_classifier_inference.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/333.
> Modify classifier scripts

- .github/workflows/gpuci.yml
- Dockerfile
This will build a `buildcache` image on `main` that PRs then can benefit from.
```python
```
> ci: Run on main

- nemo_curator/scripts/find_exact_duplicates.py
This PR is to fix `gpu_exact_dups` mention in this issue, https://github.com/NVIDIA/NeMo-Curator/issues/350
Referencing these 2 commits:
- https://github.com/NVIDIA/NeMo-Curator/commit/1c73adeedb20df33cebe45cf94c5a3109b10c3b5#diff-67ff83fb9bb047c0cc82578699f04307c242ecb4249937c971dbf644494b56edR43
- https://github.com/NVIDIA/NeMo-Curator/commit/5e46cd8df7bf16b5442e8614b3ce45421eba3ebf
I noticed the `args.no_gpu` is a deprecated argument, however during the refactoring process, one of this argument is being left out. This blocks `gpu_exact_dups` from executing correctly.
Prereqs:
add_id is executed on the jsonl to add id for dedup
existing .jsonl files in file directory eg.books_dedup/
```
gpu_exact_dups \
--input-json-id-field="nemo_id" \
--input-data-dir=books_dedup/ \ …
```
> Fix `gpu_exact_dups` due to deprecated flag

- .github/workflows/release.yml
- Dockerfile
The release workflow was not yet able to handle the `devN` segment properly. A prerelease must reset it back to `dev0`. This is done with version `v0.12.0`.
```python
```
> ci: Bump release workflow to allow of `devN` semver

- .github/workflows/release-freeze.yml
- .github/workflows/release.yml
This workflow is triggered manually. It branches `main` into a new branch of `rX.Y.Z.` based on the semver of its cut-off commit. Then, it attempts a version bump in `main based on the workflow input (major/minor) via a PR into `main`. Finally, it shoots a notification into the main Slack channel
```python
```
> ci: Add code-freeze workflow

- .github/workflows/cherry-pick-release-commit.yml
Once we have cut-off the release branch, we can automatically cherry pick fixes into it by assigning a label `$RELEASE_BRANCH_NAME` to the PR that goes into `main`. Once it hits `main`, the automation will attempt a cherry pick via PR into the release branch. If it fails due to an impossible 3-way merge, it sends a Slack alert into the CI channel with our user-group mention so that we can notify the original PR author
```python
```
> ci: Add cherry pick workflow

- nemo_curator/classifiers/__init__.py
- nemo_curator/classifiers/aegis.py
- nemo_curator/classifiers/base.py
Copy of https://github.com/NVIDIA/NeMo-Curator/pull/325.
Awaiting Hugging Face release here: https://huggingface.co/nvidia/FineTune-Guard
> Add support for FineTune-Guard classifier

- Dockerfile
Realised that while we're installing cuda-12.5.1 in the CI image, the conda installations are all over the place and some of them are being picked up from conda-forge rather than nvidia. (IIUC -c A -c B, A takes precedence over B, and in our case conda-forge might have older versions of packages)
Secondly if we wish to use UDFs on `dask_cudf` we need `NVVM`. The place where I needed it was hack for #417
> Dockerfile should use the correct nvidia channel to install libcu*

- tutorials/dapt-curation/README.md
- tutorials/dapt-curation/code/configs/text_semantic_dedupe_config.yaml
- tutorials/dapt-curation/code/main.py
- tutorials/dapt-curation/code/requirements.txt
- tutorials/dapt-curation/code/utils.py
The PR adds 
- Versions for installations edits in requirements.txt for pip packages
- `fuzzy_dedupe` module implementation to DAPT data curator tutorial for chipNeMo. It performs Fuzzy Deduplication on code as well as text documents from Wikipedia and Arxiv sources.
- `semantic_dedupe` module implementation to DAPT data curator tutorial for chipNeMo. It performs Semantic Deduplication on text documents from Wikipedia and Arxiv sources.
```
cd NeMo-Curator/tutorials/dapt-curation/code/
python main.py
```
- [ X] I am familiar with the [Contributing Guide](https://github.com/NVIDIA/NeMo-Curator/blob/main/CONTRIBUTING.md).
- [ X] New or Existing tests cover these changes.
- [ X] The documentation is up to date with these changes.
> Adding fuzzy and semantic dedupe

- nemo_curator/package_info.py
We need to move package version as  `0.6.0rc0` already got released
```python
```
> chore: Bump to `0.6.0rc1`

- .github/workflows/gpuci.yml
This provides a new input `use_cache: [boolean]` which we can use to create nightly builds from scratch 
```python
```
> ci: Bump `_build_container` workflow

- tests/test_fuzzy_dedup.py
24.12 moves to using the new minhash_permuted api which use different seed values and produce different minhash values. For tests with few minhashes `3` and strings
`"The quick brown fox jumps over the lazy dog."`
`"The quick black cat jumps over the lazy dog."`
Given 12 ngrams do not match each other there is a chance that a few hashes do not have any overlaps leading to failing tests.
Increased the number of minhashes to increase the probability of a collision in the tests.
> Update fuzzy dedup test args to account for minhash algo changes.

- Dockerfile
Since we have two `FROM`s in our Dockerfile, to reference the first build arg (CUDA_VER) we need to redeclare it as an arg again.
```python
```
> Bug fix in dockerfile ARG vs ENV var

- .github/workflows/gpuci.yml
- nemo_curator/classifiers/aegis.py
- pyproject.toml
- tests/test_classifiers.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/405.
Closes https://github.com/NVIDIA/NeMo-Curator/issues/419.
> Add `tests/test_classifiers.py` PyTests

- nemo_curator/datasets/doc_dataset.py
- nemo_curator/datasets/parallel_dataset.py
- nemo_curator/download/arxiv.py
- nemo_curator/download/commoncrawl.py
- nemo_curator/download/doc_builder.py
- nemo_curator/download/wikipedia.py
- nemo_curator/modules/dataset_ops.py
- nemo_curator/utils/distributed_utils.py
- nemo_curator/utils/file_utils.py
- tests/test_io.py
- tests/test_read_data.py
- tests/test_separate_by_metadata.py
- tests/test_shuffle.py
- tutorials/peft-curation-with-sdg/docbuilder.py
- tutorials/peft-curation-with-sdg/synthetic_gen.py
- tutorials/peft-curation/docbuilder.py
- tutorials/tinystories/docbuilder.py
Resolves https://github.com/NVIDIA/NeMo-Curator/issues/427
```python
```
> Change filename column name to file_name

- nemo_curator/modules/__init__.py
Reorders import to move filter import after all cugraph imports due to this issue: https://github.com/rapidsai/cugraph/issues/2718.
The PyTorch import comes from `nemo_curator/__init__.py` -> `nemo_curator/modules/__init__.py` -> `nemo_curator/modules/filter.py` -> `from nemo_curator.filters import DocumentFilter` -> `nemo_curator/filters/__init__.py` -> `nemo_curator/filters/classifier_filter` -> `nemo_curator/filters/models/qe_models/py` -> `comet = safe_import("comet", msg=COMET_IMPORT_MSG)`.
This error only occurs when using the optional `comet` package.
N/A
> Reorder imports to work around cugraph bug for comet

- nemo_curator/classifiers/base.py
- tests/test_classifiers.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/425.
> Clean up internal column logic in `_run_classifier_helper` function

- nemo_curator/utils/distributed_utils.py
By removing the `sorted(..)` in `read_data_files_per_partition` we can be sure that the input order provided by user is respected. And in case a directory is provided as an input then we are ls-ing and then sorting before reading.
Solves https://github.com/NVIDIA/NeMo-Curator/issues/486
Current flow is
1. `DocumentDataset.read_json/parquet` calls `_read_json_or_parquet`
2. `_read_json_or_parquet` which calls `read_data`
- `_read_json_or_parquet` accepts `input_files` that could be `list[files]`, `list[dir]` or `file` or `dir`
- if it's a `dir` or `list[dir]` it calls `get_all_files_paths_under` which has an implicit `sort`
3. `read_data` accepts `list[files]` and calls `read_data_blocksize` or read_data_files_per_partition`
4. 
1. `read_data_files_per_partition` performs a sort
2. …
> Respect file order in `DocumentDataset.read_`

- .github/workflows/test.yml
- Dockerfile
- README.md
- docs/user-guide/image/gettingstarted.rst
- pyproject.toml
Updates NeMo Curator to remove the upper bound on the Python version. Eventually, we can raise the lower bound, but in the meantime while the CI is still transitioning I've left it at 3.10. All docs should be updated, please let me know if I missed something.
Another minor change I did was a request from @ericharper to reorder the author list. He noticed that the first author appears as the point of contact on the pypi page (https://pypi.org/project/nemo-curator/) and he prefers that I be the point of contact over Joseph since he is no longer involved in the project.
N/A
> Update to support Python 3.12

- .github/workflows/test.yml
Adds Python 3.10 to the CPU unit test matrix.
N/A
> Add Python 3.10 to unit test matrix

- config/sem_dedup_config.yaml
- docs/user-guide/semdedup.rst
- nemo_curator/modules/config.py
- nemo_curator/modules/semantic_dedup/embeddings.py
- nemo_curator/modules/semantic_dedup/semdedup.py
- nemo_curator/scripts/semdedup/compute_embeddings.py
- tutorials/dapt-curation/README.md
- tutorials/dapt-curation/code/configs/text_semantic_dedupe_config.yaml
- tutorials/dapt-curation/code/main.py
- tutorials/dapt-curation/code/utils.py
The semantic deduplication portion of the DAPT tutorial is currently failing with a `ValueError("'category' column dtypes are currently not supported by the gpu accelerated parquet writer")`. A quick way to avoid this error is to avoid writing the embeddings to disk.
> Fix DAPT tutorial

- .github/workflows/build-test-publish-wheel.yml
- MANIFEST.in
- pyproject.toml
> ci: Pin twine to `6.0.1`

- docs/user-guide/api/dask.rst
- docs/user-guide/cpuvsgpu.rst
- nemo_curator/classifiers/base.py
- nemo_curator/filters/doc_filter.py
- nemo_curator/modifiers/doc_modifier.py
- nemo_curator/modules/__init__.py
- nemo_curator/modules/add_id.py
- nemo_curator/modules/base.py
- nemo_curator/modules/dataset_ops.py
- nemo_curator/modules/exact_dedup.py
- nemo_curator/modules/filter.py
- nemo_curator/modules/fuzzy_dedup/fuzzyduplicates.py
- nemo_curator/modules/modify.py
- nemo_curator/modules/semantic_dedup/semdedup.py
- nemo_curator/modules/task.py
- nemo_curator/modules/to_backend.py
- tests/test_backends.py
Refactors all modules to inherit from `nemo_curator.modules.base.Module`. With this change, the base class now checks to see if the dataframe backend for the `Module` matches what is passed in, and will throw an error prior to computation if there is a mismatch. We also prove a new module `ToBackend()` that allows easy chaining of CPU and GPU modules.
```python
from nemo_curator import Module, Sequential, ToBackend
from nemo_curator.datasets import DocumentDataset
class CPUModule(Module):
def __init__(self):
super().__init__(input_backend="pandas")
def call(self, dataset: DocumentDataset):
dataset.df["cpu_lengths"] = dataset.df["text"].str.len()
return dataset
class GPUModule(Module):
def __init__(self):
super().__init__(input_backend="cudf")
def call(self, dataset: DocumentDataset): …
```
> Enforce Dataframe Backend Checks

- nemo_curator/datasets/doc_dataset.py
- nemo_curator/utils/distributed_utils.py
- tests/test_io.py
This pull request introduces the ability to partition datasets when writing to JSONL or Parquet formats. It includes updates to the `DocumentDataset` and `write_to_disk` functions
Writing a Partitioned Dataset to Disk
This example demonstrates how to partition your output files by a specific column (here, `category`). The output directory will contain subdirectories for each unique value in the partition column.
```python
import os
import json
import pandas as pd
import dask.dataframe as dd
from nemo_curator.datasets import DocumentDataset
data = {
"id": [1, 2, 3, 4],
"category": ["A", "B", "A", "B"],
"value": [10, 20, 30, 40],
"text": [
"This is document 1",
"This is document 2",
"This is document 3",
"This is document 4"
]
}
df = pd.DataFrame(data)
ddf = dd.from_pandas(df, …
```
> Add Partition On Logic 

- .github/workflows/gpuci.yml
> ci: Limit unit-test duration

- tutorials/dapt-curation/code/docbuilder.py
- tutorials/dapt-curation/code/downloaders.py
Since https://github.com/NVIDIA/NeMo-Curator/pull/541 was merged, the download classes and functions for the text extraction step in the DAPT tutorial need to be updated.
> Fix `download_sources` for DAPT tutorial

- examples/exact_deduplication.py
- nemo_curator/modules/config.py
- nemo_curator/modules/exact_dedup.py
- nemo_curator/modules/fuzzy_dedup/fuzzyduplicates.py
- nemo_curator/utils/duplicates_removal.py
- tests/test_duplicates_removal.py
- tests/test_exact_dedup.py
Fixes a few nits from https://github.com/NVIDIA/NeMo-Curator/pull/509.
> Minor updates to duplicate removal

- nemo_curator/datasets/doc_dataset.py
- nemo_curator/download/doc_builder.py
- nemo_curator/scripts/semdedup/clustering.py
- nemo_curator/scripts/semdedup/compute_embeddings.py
- nemo_curator/scripts/semdedup/extract_dedup_data.py
- nemo_curator/utils/distributed_utils.py
- tests/test_dataset.py
- tests/test_io.py
- tests/test_read_data.py
We need an ability to read arbitrary datasets using a user defined function. 
The UDF should accept
- files: A list of file paths.
- file_type: The type of the file to read (in case you want to handle different file types differently).
- backend: pd / cudf 
- add_filename: True / False / str in which case they can use `from nemo_curator.utils.distributed_utils import _resolve_filename_col`
- columns: Can use this to define set of cols to return (output is always sorted columns)
- input_meta: Can use this for typecasting if eneded
```python
```
> Add read_custom_data to DocumentDataset

- tests/test_download.py
Remove download tests that interact with external service and have been failing.
N/A
> Remove flakey download tests

- config/sem_dedup_config.yaml
- docs/user-guide/semdedup.rst
- nemo_curator/modules/config.py
- nemo_curator/modules/semantic_dedup/semanticclusterleveldedup.py
- nemo_curator/modules/semantic_dedup/semdedup.py
- nemo_curator/scripts/semdedup/extract_dedup_data.py
- nemo_curator/utils/semdedup_utils.py
- tests/test_semdedup.py
- tutorials/dapt-curation/code/configs/text_semantic_dedupe_config.yaml
- tutorials/image-curation/image-curation.ipynb
- tutorials/peft-curation-with-sdg/config/sem_dedup_config.yaml
Resolves https://github.com/NVIDIA/NeMo-Curator/issues/520
Currently if a single cluster is large enough, we'll likely OOM since `M @ M.T` requires `N**2` storage. A batched version breaks it up into smaller batches B and performs `M @ B.T`. The only thing we need to be careful is how to zero out the diagonals and get the upper triangular matrix.
1. `get_cluster_reps -> get_normalized_cluster_reps` : now **always** l2 normalize the embedding vector so that `M @ M.T` results in an absolute max value of 1
1. renamed `_semdedup` to `pairwise_similarity`
3. added tests for existing function + the batched approach.
4. default now is batched implementation
```python
```
> Add batched pairwise similarity method for Semantic Dedup

- nemo_curator/classifiers/aegis.py
- pyproject.toml
This PR fixes a bug we saw in the release container which causes cuda context being created on GPU-0. I have not been able to repro this outside this container till now.
```python3
docker run --rm -it --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 nvcr.io/nvidia/nemo:25.02
```
```python3
import time
import dask
import dask_cudf
from nemo_curator import get_client
def main():
client = get_client(cluster_type="gpu")
print(f"Client obtained: {client}")
ddf = dask.datasets.timeseries()
cudf_ddf = dask_cudf.from_dask_dataframe(ddf)
print(cudf_ddf.map_partitions(len).compute())
time.sleep(100)
if __name__ == "__main__":
main()
```
```python3
import time
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import dask
import dask_cudf
from peft import …
```
> Fix Transformers + Cuda Context bug in NeMo Curator

- .github/workflows/gpuci.yml
Currently, a user wishing to run gpuCI on a PR must remove and re-add the `gpuci` label in order to rerun it after pushing new commits. This PR allows us to autorun gpuCI when new commits are pushed, as long as the PR has the `gpuci` label on it.
> Automatically run gpuCI on PR updates

- .github/workflows/gpuci.yml
- nemo_curator/services/nemo_client.py
- nemo_curator/utils/config_utils.py
- nemo_curator/utils/distributed_utils.py
- nemo_curator/utils/file_utils.py
- nemo_curator/utils/import_utils.py
- tests/services/__init__.py
- tests/services/test_model_client.py
- tests/services/test_nemo_client.py
- tests/services/test_openai_client.py
- tests/test_classifiers.py
- tests/test_slurm.py
- tests/utils/test_bitext_distributed_utils.py
- tests/utils/test_config_utils.py
- tests/utils/test_distributed_utils.py
- tests/utils/test_download_utils.py
- tests/utils/test_file_utils.py
Adds miscellaneous unit tests to test
- `nemo_curator/services`
- `nemo_curator/nemo_run`
- `nemo_curator/utils/distributed_utils.py`
- `nemo_curator/utils/file_utils.py`
- reactivated aegis tests in `tests/test_classifiers.py`
N/A
> Add miscellaneous unit tests

- config/sem_dedup_config.yaml
- docs/user-guide/semdedup.rst
- nemo_curator/modules/config.py
- nemo_curator/modules/semantic_dedup/clusteringmodel.py
- nemo_curator/modules/semantic_dedup/semanticclusterleveldedup.py
- nemo_curator/modules/semantic_dedup/semdedup.py
- nemo_curator/scripts/semdedup/clustering.py
- nemo_curator/scripts/semdedup/extract_dedup_data.py
- nemo_curator/utils/import_utils.py
- nemo_curator/utils/script_utils.py
- nemo_curator/utils/semdedup_utils.py
- tests/test_argument_helper.py
- tests/test_semdedup.py
- tutorials/dapt-curation/code/configs/text_semantic_dedupe_config.yaml
- tutorials/dapt-curation/code/utils.py
- tutorials/image-curation/image-curation.ipynb
- tutorials/peft-curation-with-sdg/config/sem_dedup_config.yaml
- tutorials/peft-curation-with-sdg/main.py
1. `compute_semantic_match_dfs` doesn't need `esp_to_extract_list` as input
2. We normalize embeddings before we perform KMeans
3. We support both L2 and Cosine Distance for `which_to_keep`
4. Intermediate output columns have changed.
Removed the following 
1. Arguments
- `sort_clusters`
- `kmeans_with_cos_dist`
- `eps_thresholds`
- `id_col_type` (in `SemanticClusterLevelDedup`)
-  `sorted_clusters_dir` (in `SemanticClusterLevelDedup`)
6. Functions
- `assign_and_sort_clusters`
- `rank_within_cluster`
- `read_cluster_embeddings_and_sort_by_id`
- `get_ids_within_cluster`
- `_get_empty_results_df`
- `extract_pruned_data`
- `extract_dedup_data`
Now SemanticDedup is much simpler to follow
1. `ClusteringModel.__call__` performs a 
1. Embedding Normalization
2. KMeans.fit / predict
7. Computes …
> Sem Dedup Refactor (bug fixes / tests / simplifcation)

- nemo_curator/utils/semdedup_utils.py
- tests/test_semdedup.py
`cupy` doesn't support string arrays, therefore `.values` won't work as intended. 
Originally I was going to use `.to_arrow()` to solve this problem, but then i figured we could just let it be a cudf.Series
```python
```
> Semantic Dedup bug fix to support string id types

- nemo_curator/scripts/fuzzy_deduplication/minhash_lsh.py
Unintentionally in the Ruff PR looks like parser was added as a required arg in parser. This is how it was before the Ruff changes https://github.com/NVIDIA/NeMo-Curator/blame/81983ad74f59f9c9477612ce88853a186b3474b8/nemo_curator/scripts/fuzzy_deduplication/minhash_lsh.py#L83
```python
```
> Minhash Script Bugfix - removed extra argparse 

- nemo_curator/modifiers/pii_modifier.py
This PR reverts to changes made by @ayushdg in https://github.com/NVIDIA/NeMo-Curator/pull/61/files which were changed back to ruff changes
```python3
#!/usr/bin/env python3
"""
Report which physical GPU (nvidia‑smi index) each NeMo‑Curator Dask worker
is using, and assert uniqueness per host.
Duplicates across hosts are allowed; duplicates on the same host trigger
an AssertionError.
"""
from __future__ import annotations
import socket
import time
from collections import defaultdict
from nemo_curator import get_client, __version__ as curator_version
def _worker_info() -> tuple[str, int]:
"""
Runs on every Dask worker.
Returns
-------
(hostname, global_gpu_index)
hostname     – value from socket.gethostname() on that node
gpu_index    – nvidia‑smi column index of the GPU this worker owns …
```
> Revert PiiDeidentifier Import 

- pyproject.toml
Not having it does not break anything, but adding the "asyncio" marker to our `pyproject.toml` file allows us to silence the `PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html` warnings on our GPU CI.
> Add asyncio to PyTest markers

- .github/copy-pr-bot.yaml
Add initial copy-pr-bot config. Once we move to the Nvidia Github runners, this will be used to vet who's PRs are allowed to run on the CI machines. Or who can allow an external user's PR to run in the CI pipeline.
I added names based on members who had write and admin access.
```python
```
> Add initial copy-pr-bot config

- .github/copy-pr-bot.yaml
Always require using the /ok to test comment to run tests
Currently, with the copy-pr-bot config, every commit will trigger GPU tests to run. To align more closely with the gpu-ci label, we'll update the copy-pr-bot config so that the developer needs to intentionally comment `/ok to test` to trigger.
```python
```
> ci: Always require using the /ok to test comment to run tests

- .github/workflows/gpuci.yml
Fix gpu ci on push to main. The evaluation of the PR info output was happening on the push to main still, causing the CI job to fail there.
```python
```
> Fix gpu ci on push to main

- nemo_curator/_compat.py
- nemo_curator/modules/semantic_dedup/clusteringmodel.py
Existing implementation is both convoluted and can be very slow [unless a user explicitly does `to_backend("cudf")` (read point 1 below).]
A simpler implementation performs similar even when user doesn't do the `to_backend(..)`. 
The code has been testing on 37mn embedding dataset (80gb worth of data) on 7 GPUs and much smaller dataset of 2gb on both Rapids 25.02 and Rapids 25.06.
Here is the GPU utilization for 90 gb of embeddings where we see that during KMeans.fit it spikes to 2x
Here are the results which show that our existing implementation times out when we don't do `to_backend('cudf')` 
Our existing codes flow was as follows
```python
embeddings_df = DocumentDataset.read_parquet(...., backend="cudf", blocksize or fpp).df
embeddings_df = embeddings_df.to_backend("pandas").persist() …
```
> Simplifying clustering logic

- nemo_curator/filters/heuristic_filter.py
- nemo_curator/utils/text_utils.py
Fix typo. `langauges` should be `languages`.
> Fix language typo in docstrings

- tutorials/nemotron-cc/nemotron_cc.ipynb
Fixed URL for Fasttext language identification model download
- [✓ ] I am familiar with the [Contributing Guide](https://github.com/NVIDIA/NeMo-Curator/blob/main/CONTRIBUTING.md).
- [✓] New or Existing tests cover these changes.
- [✓ ] The documentation is up to date with these changes.
> Fix fasttext download URL

- .github/workflows/gpuci.yml
Latest update of NeMo-FW-CI-templates (https://github.com/NVIDIA/NeMo-FW-CI-templates/compare/v0.34.0...v0.35.0) adds an option to enable a pull-through cache for images on public dockerhub.
This should increase resiliency of the docker build
```python
```
> ci: Enable pull-cache

- examples/exact_deduplication.py
- examples/fuzzy_deduplication.py
- tutorials/dapt-curation/code/utils.py
- tutorials/multimodal_dapt_curation/curator/utils.py
- tutorials/tinystories/main.py
Closes #719  and other places where we were using the new `remove(..)` api but not relying on the return type being DocDataset but rather expected it to be dask.dataframe
```python
```
> Using DocumentDataset after removal in tutorials / examples

- nemo_curator/package_info.py
[🤖]: Howdy folks, let's bump NeMo Curator to `0.10.0rc0.dev0` !
```python
```
> chore: Version bump to 0.10.0rc0.dev0

- .github/workflows/cherry-pick-release-commit.yml
Enable cherry-pick to ray-api
```python
```
> Enable cherry-pick to ray-api

- .github/workflows/gpuci.yml
- .github/workflows/test.yml
- tests/test_download.py
Add placeholder codecov check for when tests do not run
If no test coverage is uploaded, then the `codecov/patch` status will never exist. So we add a placeholder status check using the same name for when tests do not run.
Here is an example when I forced the tests to be skipped:
* Lastly, added a `gpu-ci-result` job so that it always runs even if gpu job is skipped if it's a docs only case. This would be good to have to enable a status check on it.
* Updated cpu tests to run all PR events not just labeld and synchronized
```python
```
> ci: Add placeholder codecov check for when tests do not run

- ray-curator/pyproject.toml
- ray-curator/ray_curator/stages/download/text/wikipedia/extract.py
- ray-curator/ray_curator/stages/download/text/wikipedia/url_generation.py
- ray-curator/tests/stages/download/text/wikipedia/test_iterator.py
- ray-curator/tests/stages/download/text/wikipedia/test_url_generation.py
- Removed redundant return statement in `WikipediaExtractor` class.
- Simplified status check for dump data in `WikipediaUrlGenerator` by directly accessing the dictionary keys.
- Updated logging level in tests to ensure accurate assertions on log calls.
- Enhanced test cases for URL generation to cover various dump statuses.
These changes improve code clarity and maintainability while ensuring robust error handling in the Wikipedia download and extraction process.
```python
```
> Fixing tests

- ray-curator/pyproject.toml
- ray-curator/tests/backends/test_integration.py
In 2.47.1 we had an issue with StreamingRepartition being fused with remaining tasks. Since this was merged https://github.com/ray-project/ray/issues/54431 we expect no fusion.
```python
```
> Update ray version to 2.48

- ray-curator/ray_curator/__init__.py
- ray-curator/ray_curator/stages/text/classifiers/aegis.py
- ray-curator/ray_curator/stages/text/classifiers/base.py
- ray-curator/ray_curator/stages/text/classifiers/prompt_task_complexity.py
- ray-curator/ray_curator/stages/text/embedders/__init__.py
- ray-curator/ray_curator/stages/text/embedders/base.py
- ray-curator/ray_curator/stages/text/embedders/utils.py
- ray-curator/ray_curator/stages/text/models/model.py
- ray-curator/tests/stages/text/embedders/__init__.py
- ray-curator/tests/stages/text/embedders/test_base.py
- ray-curator/tests/stages/text/embedders/test_utils.py
Extends current `models/model.py` and adds an embedding model which supports mean_pooling and last_token.
Can be used to generate embeddings that will be used in SemDedup
```python
```
> Add Text Embedding Model

- nemo_curator/utils/distributed_utils.py
If blocksize is set instead of files_per_partition, this line raised an exception.
```python
```
> Fix exception when blocksize is set

- ray-curator/ray_curator/pipeline/pipeline.py
- ray-curator/tests/pipelines/test_pipelines.py
Updates pipeline.run to use a xenna executor by default. This allows for most use cases users being able to call `pipeline.run()` without working with executors at all.
```python
pipleline.run(executor=XennaExecutor())
pipeline.run()
```
> Update pipeline run to use xenna executor by default

- ray-curator/ray_curator/stages/video/clipping/transnetv2_extraction.py
- ray-curator/ray_curator/stages/video/clipping/video_frame_extraction.py
- ray-curator/ray_curator/utils/nvcodec_utils.py
Catch the Runtime Error when import  PyNvcFrameExtractor failed due to unsupported hardware.
```python
```
> Catch runtime error for PyNvcFrameExtractor

- nemo_curator/backends/experimental/ray_data/executor.py
This shouldn't be an issue in current pipeline at all because we start with EmptyTask always i.e. num_blocks==1.
However when we give ray data N tasks as initial tasks (e.g. in removal workflow) then we want it to consider all of them as separate blocks, i.e. increasing parallelism.
```python
```
> Ray Data should set num_blocks=len(tasks)

- .github/actions/test-template/action.yml
- .github/workflows/cicd-main.yml
> ci: Add back gpu coverage report

- nemo_curator/backends/experimental/ray_data/executor.py
Sets `DataContext.get_current().enable_fallback_to_arrow_object_ext_type = True` inside RayDataExecutor
This setting should have no performance impact (since by default the value is None, so its treated as True), but only logging impact.
See this code path
https://github.com/ray-project/ray/blob/d13aa963f94df3d1e0424009d638e3aa46441be5/python/ray/air/util/tensor_extensions/arrow.py#L155-L198
```python
```
> Make Ray Datas log less verbose

- nemo_curator/backends/experimental/ray_actor_pool/executor.py
- tests/backends/experimental/ray_actor_pool/executor.py
- tests/backends/experimental/ray_actor_pool/test_executor.py
- tests/conftest.py
- tests/stages/deduplication/semantic/test_kmeans.py
Xenna implicitly sets `os.environ["RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES"]` on client. This means RayActorPool when starting after Xenna won't be able to allocate `CUDA_VISIBLE_DEVICE` on its own. This could result in RAFT Actor Pool failing 
```python
client.start() # noset hasn't been defined
run_xenna() # noset HAS been defined on client but not on workers
run_kmeans()  # same as above, but since its not on workers this works fine
client.stop() # all workers die; noset is still present on client
client.start() # noset is now propogated to workers too
run_kmeans() # fails
```
> Allow RayActorPool (RAFT) to run after Xenna
