README.md
Currently NeMo Curator is only tested with Ubuntu & does not work with windows like it's come up in #76. This PR aims to update the documentation to reflect OS requirements and GPU requirements.
N/A
=> Update requirements documentation.

README.md
Fix https://github.com/NVIDIA/NeMo-Curator/issues/116. Broken link in readme.md for task-decontamination.
=> Fix #116. Fix task-decontamination broken links

tutorials/nemotron_340B_synthetic_datagen/README.md, tutorials/nemotron_340B_synthetic_datagen/synthetic_preference_data_generation_nemotron_4_340B.ipynb
Adding a Synthetic Dataset Generation tutorial leveraging Nemotron-4 340B through `build.nvidia.com`.
=> Nemotron 340 SDG Pipeline Tutorial

nemo_curator/modules/semantic_dedup.py, nemo_curator/utils/semdedup_utils.py, tests/test_semdedup.py
=> [REVIEW] Fix SemDedup bugs

nemo_curator/scripts/domain_classifier_inference.py, nemo_curator/scripts/find_exact_duplicates.py, nemo_curator/scripts/fuzzy_deduplication/compute_minhashes.py, nemo_curator/scripts/fuzzy_deduplication/connected_components.py, nemo_curator/scripts/fuzzy_deduplication/minhash_lsh.py, nemo_curator/scripts/quality_classifier_inference.py, nemo_curator/utils/distributed_utils.py, nemo_curator/utils/script_utils.py
This PR prevent plugging an allocator twice
=> Prevent plugging an allocator twice

docs/README.md, docs/user-guide/index.rst, docs/user-guide/nextsteps.rst
Adds information on what users of NeMo Curator can do after curating their data.
N/A
=> Add next steps section

tutorials/peft-curation-with-sdg/README.md, tutorials/peft-curation-with-sdg/config/sem_dedup_config.yaml, tutorials/peft-curation-with-sdg/docbuilder.py, tutorials/peft-curation-with-sdg/filters.py, tutorials/peft-curation-with-sdg/main.py, tutorials/peft-curation-with-sdg/modifiers.py, tutorials/peft-curation-with-sdg/synthetic_gen.py
This tutorial demonstrates the usage of NeMo Curator's Python API data curation as well as synthetic
data generation, and qualitative score assignment to prepare a dataset for parameter-efficient fine-tuning (PEFT) of LLMs.
Included in README.md
=> [Tutorials] Synthetic data generation + reward model + curation for PEFT

docs/user-guide/distributeddataclassification.rst, examples/domain_classifier_example.py, examples/quality_classifier_example.py, nemo_curator/modules/distributed_data_classifier.py, nemo_curator/scripts/domain_classifier_inference.py, nemo_curator/scripts/quality_classifier_inference.py, nemo_curator/utils/script_utils.py, tutorials/distributed_data_classification/distributed_data_classification.ipynb
Closes https://github.com/NVIDIA/NeMo-Curator/issues/72
Closes https://github.com/NVIDIA/NeMo-Curator/issues/71
https://huggingface.co/nvidia/domain-classifier
=> HuggingFace support for Domain Classifier

docs/user-guide/syntheticdata.rst
Updates the synthetic data generation documentation page to include everything that was added in 24.07.
N/A
=> Update synth docs

README.md, docs/user-guide/semdedup.rst
This PR adds Semantic Deduplication Documentation.
=> Semantic Deduplication Documentation

README.md, tutorials/peft-curation-with-sdg/README.md, tutorials/peft-curation-with-sdg/main.py, tutorials/peft-curation-with-sdg/synthetic_gen.py, tutorials/peft-curation/README.md, tutorials/tinystories/README.md
* Add suppurt for SDG using LLaMa 3.1 405B
* Update instructions
* Improve error handling
* Update some of the README.md files throughout the repo
=> [Tutorials] Add LLaMa 3.1 405B to the SDG tutorial

CONTRIBUTING.md, README.md
Adds some more details to the README and CONTRIBUTING files based on issues we've seen users and contributors run into.
N/A
=> Clean up README and CONTRIBUTING

docs/user-guide/api/classifiers.rst, docs/user-guide/distributeddataclassification.rst
I missed reorganizing the classifiers in the API docs when I merged them in. Also I caught another documentation whitespace error when I was building the docs.
N/A
=> Fix a few bugs with classifier API docs

docs/user-guide/distributeddataclassification.rst, examples/classifiers/quality_example.py, nemo_curator/classifiers/base.py, nemo_curator/classifiers/domain.py, nemo_curator/classifiers/quality.py, nemo_curator/scripts/classifiers/quality_classifier_inference.py, tutorials/distributed_data_classification/distributed_data_classification.ipynb
Closes https://github.com/NVIDIA/NeMo-Curator/issues/167
=> HuggingFace support for Quality Classifier

tutorials/single_node_tutorial/single_gpu_tutorial.ipynb
1. Commit to fix bug #185.
2. Commit to fix bug #183.
3. Comment out optional result verification cells to avoid similar issues
4. Update notebook for latest NeMo Curator version
```
=> Fix bug #183 and bug #185

nemo_curator/filters/code.py, tests/test_filters.py
Speeding up this method, while removing statistics package
=> Speed up _line_statistics

examples/translation_example.py, tutorials/single_node_tutorial/single_gpu_tutorial.ipynb
This PR adds the translate example and replaces  https://github.com/NVIDIA/NeMo-Curator/pull/189. 
Have cleaned up the PR a bit and fixed bugs i found while testing.
=> [REVIEW] Add Translate Example

nemo_curator/classifiers/domain.py, nemo_curator/classifiers/quality.py
Fixes an issue where the labels may not match up properly with the indices of the `label2id` in the classifiers.
=> Sort labels

docs/user-guide/index.rst
This PR closes https://github.com/NVIDIA/NeMo-Curator/issues/197
=> Add semededup documentation to index.html

docs/user-guide/index.rst
=> Add SDG to sidebar

nemo_curator/modules/add_id.py, nemo_curator/scripts/add_id.py, nemo_curator/scripts/fuzzy_deduplication/map_buckets.py, nemo_curator/utils/script_utils.py
Addresses #142, #146, and #149.
Same as before
=> Fix issues from RPV2 Tutorial

setup.py
This PR upgrades the crossfit version being used in NeMo-Curator.
=> Upgrade crossfit version

tutorials/synthetic-data-hello-world/Synthetic Data Generation - Hello World Examples.ipynb
Fixing bug due to missing `await`.
=> Fixing missing `await` in Code Cell.

docs/user-guide/syntheticdata.rst
=> Update SDG Documentation

docs/user-guide/semdedup.rst, nemo_curator/scripts/semdedup/README.md
Closes https://github.com/NVIDIA/NeMo-Curator/issues/203
=> Update SemDedup docs

tutorials/single_node_tutorial/single_gpu_tutorial.ipynb
This PR is to 
1. fix bug #210 
2. remove unused helper function
=> Fix Bug #210 

nemo_curator/scripts/fuzzy_deduplication/minhash_lsh.py
Fixes the id field bug in the lsh script. Tested and verified the fix works.
N/A
=> Fix id field

tutorials/synthetic-preference-data/synthetic_preference_data_generation_llama_3_1_405b.ipynb
=> Fixing Model Address

tutorials/synthetic-retrieval-evaluation/DeDup.py
Fix #264. Scikit-learn is not expecting anymore the "affinity parameter"
=> Fix 264. Incorrect affinity parameter

setup.py
=> Add spacy<3.8 pin to r0.4.1

tutorials/peft-curation-with-sdg/README.md, tutorials/peft-curation-with-sdg/main.py
Addressing some feedback from an internal review.
=> [Tutorials] Improve the usability of the SDG tutorial's command

tutorials/README.md, tutorials/zyda2-tutorial/README.md
Add links to blogs in Zyda2 tutorial
=> Add links to blogs in Zyda2 tutorial

nemo_curator/utils/distributed_utils.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/216.
=> Assert that there is at least 1 worker

nemo_curator/filters/heuristic_filter.py, nemo_curator/utils/text_utils.py, requirements/requirements.txt, tests/test_filters.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/257.
=> Japanese support for `get_word_splitter`

tests/test_semdedup.py
See https://github.com/NVIDIA/NeMo-Curator/pull/327.
=> Update `id_column` and `id_column_type` names in PyTest

.github/workflows/gpuci.yml, Dockerfile
=> ci: Run on merge commit

.github/workflows/build-test-publish-wheel.yml, Dockerfile, nemo_curator/__init__.py, nemo_curator/package_info.py, pyproject.toml
Re-opening https://github.com/NVIDIA/NeMo-Curator/pull/353.
=> Add `build-test-publish-wheel` CI file

tutorials/image-curation/image-curation.ipynb, tutorials/pretraining-data-curation/start-distributed-notebook.sh, tutorials/pretraining-vietnamese-data-curation/pretraining-vietnamese-data-curation.ipynb, tutorials/zyda2-tutorial/0_processing/process_dclm.py, tutorials/zyda2-tutorial/0_processing/process_dolma_cc.py, tutorials/zyda2-tutorial/0_processing/process_fwe2.py, tutorials/zyda2-tutorial/0_processing/process_zyda.py, tutorials/zyda2-tutorial/1_fuzzy_dedup/0_minhash.py, tutorials/zyda2-tutorial/1_fuzzy_dedup/1_lsh.py, tutorials/zyda2-tutorial/1_fuzzy_dedup/2_buckets_to_edges.py, tutorials/zyda2-tutorial/1_fuzzy_dedup/3_connected_components.py, tutorials/zyda2-tutorial/2_dupes_removal/0_id_mapping.py, tutorials/zyda2-tutorial/2_dupes_removal/1_id_conversion.py, tutorials/zyda2-tutorial/2_dupes_removal/2_compute_counts.py, tutorials/zyda2-tutorial/2_dupes_removal/3_prep_dupes.py, tutorials/zyda2-tutorial/2_dupes_removal/4_get_dupes_dclm.py, tutorials/zyda2-tutorial/2_dupes_removal/4_get_dupes_dolma-cc.py, tutorials/zyda2-tutorial/2_dupes_removal/5_get_dupes_zyda.py, tutorials/zyda2-tutorial/2_dupes_removal/remove_dupes.py, tutorials/zyda2-tutorial/3_quality_model/run_quality_classifier.py, tutorials/zyda2-tutorial/4_filtering/filter_fwe.py, tutorials/zyda2-tutorial/4_filtering/filter_quality.py
See https://github.com/NVIDIA/NeMo-Curator/pull/270.
=> Remove lingering `DASK_DATAFRAME__QUERY_PLANNING` environment variables

.github/workflows/release.yml
Update release.yml to use correct hash/commit
=> Update release.yml to use correct hash/commit

.github/workflows/release.yml
=> ci: Allow dry-run of release

nemo_curator/classifiers/__init__.py, nemo_curator/classifiers/aegis.py
See https://github.com/NVIDIA/NeMo-Curator/pull/397.
Awaiting permissions to change https://huggingface.co/nvidia/FineTune-Guard on HuggingFace.
Update: https://huggingface.co/nvidia/instruction-data-guard
=> Change `FineTuneGuardClassifier` to `InstructionDataGuardClassifier`

requirements/requirements.txt, setup.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/399
=> Add pin to NeMo Toolkit

examples/classifiers/fineweb_edu_example.py, nemo_curator/classifiers/fineweb_edu.py
See https://huggingface.co/HuggingFaceFW/fineweb-edu-classifier.
Previous PRs:
- https://github.com/NVIDIA/NeMo-Curator/pull/168
- https://github.com/NVIDIA/NeMo-Curator/pull/269
=> Update `FineWebEduClassifier` identifier

docs/user-guide/image-curation.rst, docs/user-guide/reference.rst, docs/user-guide/text-curation.rst
A new PR will update the Curator index.rst to match the requested layout.
Modified Files:
- index.rst
- image-curation.rst
- reference.rst
- text-curation.rst
Documentation update, no code changes.
repo_docs pipeline passed in staging.
=> Updating index.rst to match requested layout

.github/workflows/release.yml
=> ci: Bump release workflow

tutorials/nemo-retriever-synthetic-data-generation/retriever_evalset_generator.py
=> fixed the import bug, 5008113

.github/workflows/release.yml
=> ci: Bump release workflow (better message formatting)

nemo_curator/package_info.py
=> chore: Bump to `0.6.0rc2`

.github/workflows/release.yml, CHANGELOG.md
=> chore: update changelog 0.6.0

nemo_curator/package_info.py
=> fix: Generate version number string

.github/workflows/release.yml, CHANGELOG.md, nemo_curator/package_info.py
=> Cherry pick changelog 

nemo_curator/datasets/doc_dataset.py, tests/test_io.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/371.
=> Add `TestFileExtensions` tests

.github/workflows/gpuci.yml, Dockerfile
Reverts NVIDIA/NeMo-Curator#463
=> Revert "Run GPU Tests on Rapids Nightly at midnight UTC"

nemo_curator/package_info.py
=> chore: Update package_info.py

nemo_curator/modules/add_id.py
Ensure AddId Module has any backend
=> Ensure AddId Module has any backend

.github/workflows/release-freeze.yml
=> ci: Improvements to code-freeze

.github/workflows/release-freeze.yml
=> ci: code freeze bump

nemo_curator/package_info.py
=> chore: Version bump

tutorials/image-curation/image-curation.ipynb
Same as https://github.com/NVIDIA/NeMo-Curator/pull/549, but for r0.7.0.
=> Remove install from image tutorial

nemo_curator/classifiers/base.py, nemo_curator/classifiers/prompt_task_complexity.py
Following up on https://github.com/NVIDIA/NeMo-Curator/pull/457 and https://github.com/rapidsai/crossfit/issues/108.
=> Minor CrossFit improvements

.github/workflows/build-test-publish-wheel.yml, .github/workflows/release-freeze.yml, .github/workflows/release.yml
=> ci: Allow dry-run of code-freeze

nemo_curator/package_info.py
=> style: Fix formatting for release branch

docs/user-guide/text-cleaning.rst, nemo_curator/modifiers/unicode_reformatter.py, tests/test_cleaning.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/476.
=> Add `TextFixerConfig` to `UnicodeReformatter`

.coveragerc, .github/workflows/gpuci.yml, .github/workflows/test.yml, Dockerfile, codecov.yml
=> ci(feat): Codecov

CHANGELOG.md
=> docs: Update changelog for `0.7.0`

CHANGELOG.md
beep boop [🤖]: Hi @ko3n1g 👋,
we've cherry picked #586 into  for you! 🚀
=> Cherry pick `docs: Update changelog for `0.7.0` (586)` into `r0.7.0`

nemo_curator/package_info.py
=> chore: Release 0.7.0

nemo_curator/package_info.py
=> chore: Bump to 0.7.1

nemo_curator/classifiers/aegis.py, pyproject.toml
beep boop [🤖]: Hi @VibhuJawa 👋,
we've cherry picked #591 into  for you! 🚀
=> Cherry pick `Fix Transformers + Cuda Context bug in NeMo Curator (591)` into `r0.7.0`

tutorials/synthetic-retrieval-evaluation/DeDup.py
Fixes a rate limit issue on build.nvidia.com by limiting the number of workers.
N/A
=> Fix rate limit in SDG Retriever Eval Tutorial

tutorials/synthetic-retrieval-evaluation/DeDup.py
beep boop [🤖]: Hi @ryantwolf 👋,
we've cherry picked #600 into  for you! 🚀
=> Cherry pick `Fix rate limit in SDG Retriever Eval Tutorial (600)` into `r0.7.0`

tests/test_metrics.py
Adds tests for all the downstream tasks in Task Decontamination.
N/A
=> Add metrics tests

tutorials/dapt-curation/README.md, tutorials/dapt-curation/code/configs/text_semantic_dedupe_config.yaml, tutorials/dapt-curation/code/main.py, tutorials/dapt-curation/code/requirements.txt, tutorials/dapt-curation/code/utils.py
The PR inscludes:
1. Changes in README to install packages
2. Changes in requirements.txt for updates to the new packages
3. Changes in flags for fuzzy and semantic dedupe
```
python main.py --device "gpu"
```
- [Y] I am familiar with the [Contributing Guide](https://github.com/NVIDIA/NeMo-Curator/blob/main/CONTRIBUTING.md).
- [Y] New or Existing tests cover these changes.
- [Y]The documentation is up to date with these changes.
=> Adding signed commits for PR - Minor edits to instructions in readme, requirements, fuzzy and semantic dedupe flags #548

CHANGELOG.md
Add changelog for 0.7.1
```python
```
=> Add changelog for 0.7.1

CHANGELOG.md
beep boop [🤖]: Hi @chtruong814 👋,
we've cherry picked #613 into  for you! 🚀
=> Cherry pick `Add changelog for 0.7.1 (613)` into `r0.7.0`

nemo_curator/modules/filter.py, tests/test_filters.py
=> Making Score and Filter to accept DocumentFilter too

nemo_curator/package_info.py
=> chore: Bump to 0.8.0rc2

nemo_curator/utils/distributed_utils.py, tests/utils/test_distributed_utils.py
beep boop [🤖]: Hi @ayushdg 👋,
we've cherry picked #631 into  for you! 🚀
=> Cherry pick `Fix bug when removing extensions from a filename (631)` into `r0.8.0`

pyproject.toml
=> Pin Rapids versions to 25.02 for r0.8.0

pyproject.toml
beep boop [🤖]: Hi @ayushdg 👋,
we've cherry picked #639 into  for you! 🚀
=> Cherry pick `Pin Rapids versions to 25.02 for r0.8.0 (639)` into `r0.8.0`

nemo_curator/_compat.py, nemo_curator/log.py, nemo_curator/modifiers/__init__.py, nemo_curator/modifiers/async_llm_pii_modifier.py, nemo_curator/modifiers/c4.py, nemo_curator/modifiers/doc_modifier.py, nemo_curator/modifiers/fasttext.py, nemo_curator/modifiers/line_remover.py, nemo_curator/modifiers/llm_pii_modifier.py, nemo_curator/modifiers/markdown_remover.py, nemo_curator/modifiers/newline_normalizer.py, nemo_curator/modifiers/pii_modifier.py, nemo_curator/modifiers/quotation_remover.py, nemo_curator/modifiers/slicer.py, nemo_curator/modifiers/unicode_reformatter.py, nemo_curator/modifiers/url_remover.py, nemo_curator/services/__init__.py, nemo_curator/services/conversation_formatter.py, nemo_curator/services/model_client.py, nemo_curator/services/nemo_client.py, nemo_curator/services/openai_client.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/644
Replica of  https://github.com/NVIDIA/NeMo-Curator/pull/659 but merges to `ruff`
```python
```
=> Ruff : nemo_curator/services and nemo_curator/modifier and log.py and _compat.py 

nemo_curator/datasets/__init__.py, nemo_curator/datasets/doc_dataset.py, nemo_curator/datasets/image_text_pair_dataset.py, nemo_curator/datasets/parallel_dataset.py, nemo_curator/image/classifiers/aesthetic.py, nemo_curator/image/classifiers/base.py, nemo_curator/image/classifiers/nsfw.py, nemo_curator/image/embedders/base.py, nemo_curator/image/embedders/timm.py, nemo_curator/nemo_run/slurm.py, nemo_curator/pii/algorithm.py, nemo_curator/pii/constants.py, nemo_curator/pii/custom_batch_analyzer_engine.py, nemo_curator/pii/custom_nlp_engine.py, nemo_curator/pii/recognizers/address_recognizer.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/649.
=> Ruff formatting for `nemo_curator/datasets`, `nemo_curator/image`, `nemo_curator/nemo_run`, and `nemo_curator/pii`

nemo_curator/utils/config_utils.py, nemo_curator/utils/constants.py, nemo_curator/utils/decorators.py, nemo_curator/utils/distributed_utils.py, nemo_curator/utils/download_utils.py, nemo_curator/utils/duplicates_removal.py, nemo_curator/utils/file_utils.py, nemo_curator/utils/fuzzy_dedup_utils/id_mapping.py, nemo_curator/utils/fuzzy_dedup_utils/io_utils.py, nemo_curator/utils/fuzzy_dedup_utils/merge_utils.py, nemo_curator/utils/fuzzy_dedup_utils/output_map_utils.py, nemo_curator/utils/fuzzy_dedup_utils/shuffle_utils.py, nemo_curator/utils/gpu_utils.py, nemo_curator/utils/image/transforms.py, nemo_curator/utils/import_utils.py, nemo_curator/utils/llm_pii_utils.py, nemo_curator/utils/module_utils.py, nemo_curator/utils/script_utils.py, nemo_curator/utils/semdedup_utils.py, nemo_curator/utils/text_utils.py, tests/utils/test_distributed_utils.py
Closes https://github.com/NVIDIA/NeMo-Curator/issues/648
```python
```
=> Ruff : `nemo_curator/utils`

nemo_curator/package_info.py, nemo_curator/services/nemo_client.py, nemo_curator/synthetic/error.py, nemo_curator/utils/aegis_utils.py, tests/utils/test_bitext_distributed_utils.py, tests/utils/test_distributed_utils.py, tests/utils/test_file_utils.py
=> Ruff : Remaining Fixes

nemo_curator/_compat.py, nemo_curator/modules/fuzzy_dedup/minhash.py, tests/test_read_data.py
Now that base is 25.02+ we can get rid of conditionals for minhash API.
Also closes https://github.com/NVIDIA/NeMo-Curator/issues/557
```python
```
=> Remove conditions for Minhash

tutorials/nemo-retriever-synthetic-data-generation/README.md, tutorials/nemo-retriever-synthetic-data-generation/mine_hard_negatives.py, tutorials/nemo-retriever-synthetic-data-generation/retriever_hardnegative_miner.py
@vinay-raman Could you review the changes for the 0.8.0. There were some merge conflicts I had to manually resolve and want to make sure I didn't miss anything.
---------
```python
```
=> Cherry pick Retriever hard negative mining fix (682) into r0.8.0 

nemo_curator/synthetic/async_nemotron.py, tests/synthetic/test_async_nemotron.py
=> Adding trimming of output

CHANGELOG.md
Add 0.8.0 changelog
```python
```
=> Add 0.8.0 changelog

CHANGELOG.md
beep boop [🤖]: Hi @chtruong814 👋,
we've cherry picked #701 into  for you! 🚀
=> Cherry pick `Add 0.8.0 changelog (701)` into `r0.8.0`

nemo_curator/package_info.py
=> Publish 0.8.0

nemo_curator/package_info.py
=> Bump to 0.8.1

.github/workflows/gpuci.yml, nemo_curator/__init__.py, nemo_curator/hello.py, nemo_curator/log.py, tests/test_hello.py
Update to use nemo runners and remove unnecessary test code.
```python
```
=> c: Update to use nemo runners

nemo_curator/log.py
Accidentally left a comment in the code.  So cleaning it up now.
```python
```
=> Remove unnecessary comment

.github/workflows/gpuci.yml
=> ci: Run gputests on main

pyproject.toml, tests/test_download.py
Closes https://github.com/NVIDIA-NeMo/Curator/issues/751.
=> Fix failing Trafilatura tests for extracting Chinese and Japanese text

pyproject.toml, tests/test_download.py
beep boop [🤖]: Hi @sarahyurick 👋,
we've cherry picked #752 into  for you! 🚀
=> Cherry pick `Fix failing Trafilatura tests for extracting Chinese and Japanese text (752)` into `r0.9.0`

tutorials/distributed_data_classification/fineweb-edu-ensemble-classification.ipynb
beep boop [🤖]: Hi @abhinavg4 👋,
we've cherry picked #748 into  for you! 🚀
=> Cherry pick `fix: Update import path for _FastText in fineweb-edu-ensemble-classif… (748)` into `r0.9.0`

tests/test_download.py
beep boop [🤖]: Hi @abhinavg4 👋,
we've cherry picked #794 into  for you! 🚀
=> cp: `Add tests for safe extraction methods in test_download.py (794)` into `r0.9.0`

tests/test_classifiers.py
beep boop [🤖]: Hi @abhinavg4 👋,
we've cherry picked #774 into  for you! 🚀
=> cp: `Remove skip markers from classifier tests to enable execution on GPU (774)` into `r0.9.0`

tutorials/image-curation/image-curation.ipynb
beep boop [🤖]: Hi @sarahyurick 👋,
we've cherry picked #791 into  for you! 🚀
=> cp: `Uncomment pip install comment in Image Tutorial (791)` into `r0.9.0`

tutorials/single_node_tutorial/single_gpu_tutorial.ipynb
beep boop [🤖]: Hi @sarahyurick 👋,
we've cherry picked #802 into  for you! 🚀
=> cp: `Nit fixes in Single GPU Tutorial (802)` into `r0.9.0`

pyproject.toml
=> Set upperbound on datasets version

tutorials/multimodal_dapt_curation/README.md, tutorials/multimodal_dapt_curation/curator/README.md, tutorials/multimodal_dapt_curation/curator/requirements.txt, tutorials/multimodal_dapt_curation/ingest/README.md
This PR addresses the comments in the VDR
```
cd ingest/
python main.py --analyze --display
cd curator/
python main.py --protocol "tcp" --rmm-pool-size "1GB" --device "gpu"
```
- [ Y] I am familiar with the [Contributing Guide](https://github.com/NVIDIA/NeMo-Curator/blob/main/CONTRIBUTING.md).
- [Y ] New or Existing tests cover these changes.
- [ Y] The documentation is up to date with these changes.
=> Multimodal dapt curation edits

tutorials/multimodal_dapt_curation/README.md, tutorials/multimodal_dapt_curation/curator/README.md, tutorials/multimodal_dapt_curation/curator/requirements.txt, tutorials/multimodal_dapt_curation/ingest/README.md
beep boop [🤖]: Hi @ruchaa-apte 👋,
we've cherry picked #813 into  for you! 🚀
=> cp: `Multimodal dapt curation edits (813)` into `r0.9.0`

tutorials/synthetic-data-hello-world/README.md, tutorials/synthetic-data-hello-world/Synthetic Data Generation - Hello World Examples.ipynb
beep boop [🤖]: Hi @Maghoumi 👋,
we've cherry picked #820 into  for you! 🚀
=> cp: `[Tutorials] Update the model specs in the SDG Hello World notebook (820)` into `r0.9.0`

.github/copy-pr-bot.yaml
beep boop [🤖]: Hi @suiyoubi 👋,
we've cherry picked #841 into  for you! 🚀
=> cp: `chore: Add new trustees and vetters to the copy-pr-bot configuration (841)` into `ray-api`

.github/workflows/close-inactive-issue-pr.yml, .github/workflows/community-bot.yml
beep boop [🤖]: Hi @ko3n1g 👋,
we've cherry picked #846 into  for you! 🚀
=> cp: `ci: Add community-bot (846)` into `ray-api`

CHANGELOG.md
=> docs: changelog update

CHANGELOG.md
beep boop [🤖]: Hi @lbliii 👋,
we've cherry picked #860 into  for you! 🚀
=> cp: `docs: changelog update (860)` into `r0.9.0`

nemo_curator/package_info.py
=> Update curator version

ray-curator/ray_curator/stages/io/reader/file_partitioning.py
Fix the broken unit test
```python
```
=> File Partition Edge Case Fix

tutorials/curator-llm-pii/PII-LLM-modification-Enron.ipynb, tutorials/curator-llm-pii/PII-LLM-modification-tutorial.ipynb, tutorials/curator-llm-pii/README.md
beep boop [🤖]: Hi @aadesoba-nv 👋,
we've cherry picked #868 into  for you! 🚀
=> cp: `update LLM PII redaction file - fix issue 828 (868)` into `ray-api`

docs/conf.py, docs/versions1.json
- Corrects conf.py to match version switcher
- Adds GitHub icon with a direct link to NeMo Curator GitHub
- Corrects versions1.json to the proper format
Documentation correction.
=> docs: Updating version switcher

docs/reference/index.md
beep boop [🤖]: Hi @lbliii 👋,
we've cherry picked #865 into  for you! 🚀
=> cp: `docs: api link fixes (865)` into `ray-api`

examples/experimental_scripts/README.md
=> docs: add README for experimental scripts directory

docs/about/index.md
=> verbiage for marketing

ray-curator/pyproject.toml, ray-curator/uv.lock
=> ci: Fix vllm version

ray-curator/pyproject.toml, ray-curator/uv.lock
=> ci: Pin cosmos xenna

.github/workflows/cicd-main.yml, docker/Dockerfile, uv.lock
=> ci: Re-enable gpu testing

nemo_curator/stages/text/deduplication/removal_workflow.py, tests/stages/text/deduplication/test_removal_workflow.py
=> Bug fix in removal write kwargs + add input_task_limit in removal

pyproject.toml, uv.lock
=> ci: Pin transformers

nemo_curator/package_info.py, pyproject.toml, uv.lock
=> Bump version to 1.0.0rc0.dev0

nemo_curator/__init__.py, pyproject.toml
Should fix (hopefully) the wheel build workflow failures.
```python
```
=> Include package info in init

docker/Dockerfile
beep boop [🤖]: Hi @thomasdhc 👋,
we've cherry picked #1016 into  for you! 🚀
=> cp: `ci: Add build id to dockerfile (1016)` into `r1.0.0`

nemo_curator/stages/deduplication/semantic/pairwise.py, nemo_curator/stages/deduplication/semantic/workflow.py, nemo_curator/stages/text/deduplication/semantic.py, tests/stages/text/deduplication/test_semantic.py
beep boop [🤖]: Hi @praateekmahajan 👋,
we've cherry picked #1000 into  for you! 🚀
=> cp: `Add TextSemanticDeduplicationWorkflow (1000)` into `r1.0.0`

nemo_curator/backends/experimental/ray_data/executor.py
beep boop [🤖]: Hi @praateekmahajan 👋,
we've cherry picked #1018 into  for you! 🚀
=> cp: `Make Ray Datas log less verbose (1018)` into `r1.0.0`

nemo_curator/utils/file_utils.py, tests/stages/text/io/writer/test_jsonl.py, tests/stages/text/io/writer/test_parquet.py
beep boop [🤖]: Hi @VibhuJawa 👋,
we've cherry picked #1025 into  for you! 🚀
=> cp: `[REVIEW] Add minor overwrite mode bug fix and tests (1025)` into `r1.0.0`

tutorials/text/peft-curation/README.md, tutorials/text/peft-curation/main.py, tutorials/text/tinystories/README.md, tutorials/text/tinystories/main.py
beep boop [🤖]: Hi @sarahyurick 👋,
we've cherry picked #1021 into  for you! 🚀
=> cp: `Small updates for PEFT and Tinystories tutorials (1021)` into `r1.0.0`

docs/reference/index.md, nemo_curator/backends/experimental/ray_data/executor.py, nemo_curator/backends/xenna/executor.py
beep boop [🤖]: Hi @Copilot 👋,
we've cherry picked #1036 into  for you! 🚀
=> cp: `Check codebase for typos and fix identified issues (1036)` into `r1.0.0`

tutorials/image/getting-started/README.md
beep boop [🤖]: Hi @Copilot 👋,
we've cherry picked #1050 into  for you! 🚀
=> cp: `Fix image curation tutorial batch sizes for typical GPUs (1050)` into `r1.0.0`

pyproject.toml, uv.lock
=> ci: Use pytest-cov

CONTRIBUTING.md
Updates contribution guide with some sections from the previous release that were missed. 
Fixes #1047 
N/A
=> update contribution guide 

nemo_curator/backends/experimental/ray_actor_pool/executor.py, tests/backends/experimental/ray_actor_pool/test_executor.py, tests/stages/deduplication/semantic/test_kmeans.py
beep boop [🤖]: Hi @praateekmahajan 👋,
we've cherry picked #1059 into  for you! 🚀
=> cp: `Allow RayActorPool (RAFT) to run after Xenna (1059)` into `r1.0.0`

.github/workflows/cicd-main.yml, docker/common/install_ffmpeg.sh
=> ci: Remove texinfo from ffmpeg install

pyproject.toml, uv.lock
beep boop [🤖]: Hi @thomasdhc 👋,
we've cherry picked #1072 into  for you! 🚀
=> cp: `ci: Skip kaldiio installation (1072)` into `r1.0.0`

pyproject.toml
```python
```
- [N/A] New or Existing tests cover these changes.
- [N/A] The documentation is up to date with these changes.
=> Add managed option to tool.uv configuration

tutorials/audio/fleurs/pipeline.py
=> typo fix in tutorial script

docker/Dockerfile
beep boop [🤖]: Hi @thomasdhc 👋,
we've cherry picked #1091 into  for you! 🚀
=> cp: `ci: Prune unused cache entries (1091)` into `r1.0.0`

tutorials/image/getting-started/README.md, tutorials/image/getting-started/image_curation_example.py, tutorials/image/getting-started/image_dedup_example.py
beep boop [🤖]: Hi @huvunvidia 👋,
we've cherry picked #1094 into  for you! 🚀
=> cp: `Addressing VDR comments (1094)` into `r1.0.0`

tests/models/test_internvideo2.py, tests/models/test_internvideo2_mm.py
beep boop [🤖]: Hi @suiyoubi 👋,
we've cherry picked #1111 into  for you! 🚀
=> cp: `Skip IV2 Unit Test if package not installed (1111)` into `r1.0.0`

nemo_curator/stages/audio/inference/asr_nemo.py, tests/stages/audio/inference/test_asr_nemo.py, tutorials/audio/fleurs/README.md, tutorials/audio/fleurs/pipeline.py
beep boop [🤖]: Hi @Ssofja 👋,
we've cherry picked #1113 into  for you! 🚀
=> cp: `Audio curation improvements (1113)` into `r1.0.0`

.github/workflows/cicd-main.yml, .gitignore, external/intern_video2_installation.sh, tutorials/video/getting-started/video_split_clip_example.py
beep boop [🤖]: Hi @suiyoubi 👋,
we've cherry picked #1112 into  for you! 🚀
=> cp: `Add iv2 install guide and guard import (1112)` into `r1.0.0`

docs/about/concepts/video/abstractions.md, docs/curate-video/process-data/frame-extraction.md, docs/curate-video/save-export.md, docs/get-started/video.md
beep boop [🤖]: Hi @suiyoubi 👋,
we've cherry picked #1124 into  for you! 🚀
=> cp: `Video Doc Improvement  (1124)` into `r1.0.0`

docs/_extensions/json_output/config.py, docs/_extensions/json_output/content/structured.py, docs/_extensions/json_output/core/document_discovery.py, docs/_extensions/json_output/core/hierarchy_builder.py, docs/_extensions/json_output/core/json_formatter.py, docs/_extensions/json_output/processing/processor.py, docs/_extensions/myst_codeblock_substitutions.py, docs/about/concepts/index.md, docs/about/index.md, docs/about/key-features.md, docs/about/release-notes/index.md, docs/conf.py
We don't have a super clean diff to lean on for this release, so I need extra support on getting some of these items correct. This content is just a quick first pass based on an outline we discussed with @arhamm1 
Also please look at the value prop docs (key-features) and adjust as desired.
=> about section updates

docs/_extensions/json_output/config.py, docs/_extensions/json_output/content/structured.py, docs/_extensions/json_output/core/document_discovery.py, docs/_extensions/json_output/core/hierarchy_builder.py, docs/_extensions/json_output/core/json_formatter.py, docs/_extensions/json_output/processing/processor.py, docs/_extensions/myst_codeblock_substitutions.py, docs/about/concepts/index.md, docs/about/index.md, docs/about/key-features.md, docs/about/release-notes/index.md, docs/conf.py
beep boop [🤖]: Hi @lbliii 👋,
we've cherry picked #1122 into  for you! 🚀
=> cp: `about section updates (1122)` into `r1.0.0`

CHANGELOG.md
beep boop [🤖]: Hi @lbliii 👋,
we've cherry picked #1141 into  for you! 🚀
=> cp: `changelog (1141)` into `r1.0.0`
